export const CREATE_AND_UPDATE_POKEBOARD_SUCCESS =
  'CREATE_AND_UPDATE_POKEBOARD_SUCCESS';
export const CREATE_AND_UPDATE_POKEBOARD_FAIL =
  'CREATE_AND_UPDATE_POKEBOARD_FAIL';

export const ADD_POKEMON_SUCCESS = 'ADD_POKEMON_SUCCESS';
export const ADD_POKEMON_FAIL = 'ADD_POKEMON_FAIL';

export const DELETE_POKEMON_SUCCESS = 'DELETE_POKEMON_SUCCESS';
export const DELETE_POKEMON_FAIL = 'DELETE_POKEMON_FAIL';

export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL';
